### ISSUE TITLE
建议插件命令改个名字

### ISSUE THREAD

**Issue by skywind3000** [ZSaberLv0/ZFVimTerminal#1]
这个思路还是挺好的，可以到reddit上宣传一下，不过你既然靠vim命令行输入命令，那么前缀就该短点，比如：

```VimL
:ZT ls -la
```

就行了，打着舒服点。

**Comment by skywind3000** [comment]
其实我建议你换一种体验更好，参考 emacs 的 shell，vim内建terminal的问题就是要支持全终端控制命令，保证里面可以再运行个vim那种，但是很多时候不是太必要，这样代价也很大，比如keymap全部不能用了。

我的建议就是 emacs 的 shell (不是 eshell)，半功能终端，平时进去是normal模式，可以四处移动光标，拷贝粘贴等，一旦按了 i/I/a/A/o/O/s/S/c/C 之类的，就将光标移动到接收输入的地方，让他在 insert 模式下输入，直到按回车执行本行输入的命令，或者ESC退回到 normal 模式。

**Comment by ZSaberLv0** [comment]
名字问题, 可以自己建 `:command` 或 keymap, 个人喜欢啰嗦的命名, 一是不容易冲突, 二是时间久了回来看也好懂

shell 问题, 最初就是想要这样的效果到处找插件, 但是真的不好实现, 主要的代码也是从 mattn/vim-terminal 那边抄来的而已, 而且个人希望简单粗暴的解决方案, 在尽量多的平台能用 (即使是目前这个, 也是用了一些很恶心的方式才能兼容 vim/nvim 和 linux/Windows), 至少目前算是能用的水平了, 不打算继续折腾了
